### ISSUE TITLE
req.find(query, fields, skip, limit, sort) not working with fields

### ISSUE THREAD

**Issue by notxx** [notxx/Daemon#1]
UnhandledPromiseRejectionWarning: MongoError: Failed to parse: comment: 1. 'comment' field must be of BSON type string.
    at queryCallback (/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:247:25)
    at /node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:531:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by notxx** [comment]
=> collection.find({}).skip(1).limit(1).project({b:1})
